62: Adds relative cropping support for Web-Optimized Image Delivery
wcm-io/io.wcm.handler.media pull request #63
Opened 2024-08-20 07:40 UTC by cnagel

* Use relative (percentage) parameters for cropping instead of absolute parameters. This should create more reliable renditions esp. for original images in low resolution.
* You can switch back to the old behavior by setting "Crop Option" to ABSOLUTE_PARAMETERS in the "wcm.io Media Handler Web-Optimized Image Delivery Support" OSGi configuration.

Fixes #62

2024-08-20 12:47 UTC, stefanseifert requested changes
thanks for the contribution! this looks very good.
i was able to reproduce the problem with a similar test image, and validated the solution.

(but i'm puzzled why the cropping in the edge is working like this, why is it relating at all to the cq5web rendition? maybe because cropping parameters when created by manual cropping are based on this rendition? but this should be recalculated based on original image dimensions in the application that generates the cropping parameters (we are doing this in the media handler), and not on the edge. so it looks as if the PR from adobe was only a workaround for a bug in the handling in the edge layer, and they missed to fix the root cause.)

2024-08-20 12:47 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +  private static @NotNull String createCroppingString(
i would prefer having the logic to create the relative cropping string refactored out into a separate class, with dedicated unit tests on it. ParameterMap was a very simple class before with a dedicated purpose.

actually applying the formatting of the cropping parameter value to the expected format is fine here, but the transformation of absolute values to relative should be done by a separate class - maybe we need it in other places in the future.

2024-08-20 12:47 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
why are you rounding the relative parameter values and throw away all percentage fractions? currently, it always scales to things like 12.0p, 77.0p etc. likely leading to subtle pixel differences due to rounding errors. are we limited to one fraction digit? i would feel safer having two fraction digits after the percentage value.

(one could argue that we have a rounding problem anyway, as the input values for the conversion here are already values rounded to full pixel values. but i think that's fine, as at this point we know the target resolution and the values used as input are the actual target pixel values we want to achieve. but let's not introduce more rounding uncertainty)

2024-08-20 13:23 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
I stayed close to the [Core Components](https://github.com/adobe/aem-core-wcm-components/pull/2518/files#diff-1ea580a527413c629a473c087cf47942383cdbddd5c2563622f2a67a568e88aaR218-R221) implementation. And in my example I see strange behaviour when adding fractions.
When I change width from 42p to 42.0p the service again returns a 538x402px image (instead of my requested 806x604px). Looks buggy.

2024-08-21 10:53 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
I see two different images when I use fraction or not:

https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?quality=85&preferwebp=true&crop=22.0p,0.0p,56.0p,100.0p&width=1074 only has a width of 717px.

https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?quality=85&preferwebp=true&crop=22p,0p,56p,100p&width=1074 has a width of 1074px.

2024-08-21 11:00 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
> your current implementation already used ".0" on all percentage values? see https://publish-p14256-e1375627.adobeaemcloud.com/content/rnd-mediahandler-dynamicmedia/en/no-profile.html for the output of my test application with it. it just used always ".0" instead of an actual fraction value?

This is not coming from my code. I use String.format with %.0f which only returns full digits for a double. Maybe the Adobe AssetDelivery service, which transforms the parameter.

2024-08-21 12:37 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
ah, ok. those strange handling of the fractions of percentage value does not sound very promising. sad that we cannot keep the absolute pixel calculations we had in place before.

i recommend that we introduce a new OSGi configuration parameter to configure whether absolute or relative parameters are used. default should be relative, following your initial approach with rounding the values to full values.

it's not unlikely that the fastly-based rendition generation will be further tweaked, improved or fixed by Adobe in the future.

2024-08-22 08:25 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
looking at the core component PR again https://github.com/adobe/aem-core-wcm-components/pull/2518/files#diff-1ea580a527413c629a473c087cf47942383cdbddd5c2563622f2a67a568e88aaR236-R238 they are also using a digit after the comma. i also cross-checked that the HTTP API provided by adobe for the relative cropping supports integer values as well as float values with 1 digit after the comma. this feature was added ~1 year ago in 2023. and after all, the AssetDelivery services already generates URLs with one digit after the comma, even if it's a .0 if only integers are used as input.

2024-08-22 08:38 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
i played around a bit more with the image you tested as well:
* https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?crop=22.0p,0.0p,56p,100.0p&width=1074 - returns correct width
* https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?crop=22.0p,0.0p,56.0p,100.0p&width=1074 - returns too small width

the only difference is "56p" vs. "56.0p" for the crop width. this makes no sense. although there is a coincidence that we additional provide a crop width parameter. but 1074 * 56% is is 601 and not 717px, so thats not the bug.

so my proposal is:
* we introduce an osgi config to switch between absolute and relative parameters (using relative as default)
* when using relative parameters, we use floats with one digit after the comma - as the AssetDelivery services formats the values anyway

if there is a problem left with this approach resulting in invalid images we have to get in touch with adobe. it will not be solved by using less precision in our code, as the AssetDelivery services reformats the values to use on digit in any case.

---

i will provide a commit to introduce this osgi config.

2024-08-22 09:54 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
i've updated the PR with both OSGi config, and also changed the logic to use 1 fraction for the percentage values.
cann you cross-check?

2024-08-22 09:55 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +  private static @NotNull String createCroppingString(
i've moved to the code to as separate calss

2024-08-22 11:22 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
> looking at the core component PR again https://github.com/adobe/aem-core-wcm-components/pull/2518/files#diff-1ea580a527413c629a473c087cf47942383cdbddd5c2563622f2a67a568e88aaR236-R238 they are also using a digit after the comma. i also cross-checked that the HTTP API provided by adobe for the relative cropping supports integer values as well as float values with 1 digit after the comma. this feature was added ~1 year ago in 2023. and after all, the AssetDelivery services already generates URLs with one digit after the comma, even if it's a .0 if only integers are used as input.

Yes, you are right. I just saw the `round()` method - didn't see they had an own implementation for it.

2024-08-22 11:39 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/WebOptimizedImageDeliveryCropOption.java
Why an own file and not part of the WebOptimizedImageDeliveryService interface?

2024-08-22 12:39 UTC, stefanseifert commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/WebOptimizedImageDeliveryCropOption.java
in general, i try to avoid using nested classes (or nested enum) to avoid cluttering the parent classes, leading to more even longer imports etc.

2024-08-22 14:10 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/ParameterMap.java
> +    return Math.round(fraction * 100);
> i've updated the PR with both OSGi config, and also changed the logic to use 1 fraction for the percentage values. cann you cross-check?

I can confirm, that the percents have one fraction. Looks good for me.
If you like, please merge.

2024-08-22 14:34 UTC, cnagel commented
@stefanseifert please wait with the merge.
I fear we have a wrong understanding of the image API and cropping.
Maybe the `width` parameter is used to resize a rendition and apply the cropping afterwards.
I did some tests:

To get full image in width 1920 is use cropping with 0.0p,0.0p,100.0p,100.0p. and `width=1920`
https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=0.0p,0.0p,100.0p,100.0p&quality=85&width=1920

When I add a cropping-width of 50.0p with same `width=1920` the image has a final width of 960px;
https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=25.0p,0.0p,50.0p,100.0p&quality=85&width=1920

Looks like we have not only to adopt the cropping but also the width.

2024-08-22 15:55 UTC, cnagel commented
> @stefanseifert please wait with the merge. I fear we have a wrong understanding of the image API and cropping. Maybe the `width` parameter is used to resize a rendition and apply the cropping afterwards. I did some tests:
> 
> To get full image in width 1920 is use cropping with 0.0p,0.0p,100.0p,100.0p. and `width=1920` https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=0.0p,0.0p,100.0p,100.0p&quality=85&width=1920
> 
> When I add a cropping-width of 50.0p with same `width=1920` the image has a final width of 960px; https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=25.0p,0.0p,50.0p,100.0p&quality=85&width=1920
> 
> Looks like we have not only to adopt the cropping but also the width.

Maybe also the wrong intention, sorry. Still the API chooses different renditions to apply the cropping.

But I found some kind of _dirty_ hack.
There is also a `size` parameter mentioned in the [documention](https://experienceleague.adobe.com/en/docs/experience-manager-learn/getting-started-with-aem-headless/how-to/images#query-variables).
When you adopt the width, same ugly behaviour.
But it works for me to set the original rendition width as first part of the `size` parameter and then control the size of the image with the height part.

https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=25.0p,0.0p,50.0p,100.0p&quality=85&size=1920,604 returns a 960x604px image

https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=25.0p,0.0p,50.0p,100.0p&quality=85&size=1920,302 returns a 480x302px image

works with height cropping too: https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?preferwebp=true&crop=25.0p,25.0p,50.0p,50.0p&quality=85&size=1920,151 returns a 480x151px image

now it would be interesting, how this works with images being more height than width.

2024-08-23 10:14 UTC, stefanseifert commented
i implemented an alternative approach with using "size" url parameter instead of "width", when both size and with are known in a separate branch: https://github.com/wcm-io/io.wcm.handler.media/commit/ee6b0ff5d2f9b09558456494de6ede573caf3327

and deployed it to an RDE: https://publish-p14256-e1375627.adobeaemcloud.com/content/rnd-mediahandler-dynamicmedia/en/no-profile.html

but i do not see an improvement - this image should be 1074px in width, but it is again only 716px in width:
https://publish-p14256-e1375627.adobeaemcloud.com/adobe/dynamicmedia/deliver/dm-aid--ff7ccd14-56e8-409d-a55b-4fc1b81b3c0c/annie-spratt-fhfujkkhbyu-unsplash-lowres.jpg?size=1074,604&crop=22.0p,0.0p,55.9p,100.0p&quality=85&preferwebp=true

and with size instead of width, it does no longer work to remove the fractions from the crop parameters to get the desired with.

---

ah, after re-reading you post, your hack was to actually specify a wrong width (the original width) instead of the desired width in the size parameter. hmm, probably it produces the right result currently, but we should not implement this - putting obviously wrong parameters in the URL just to tweak around bugs or insufficient logic in the server-side. this is likely to break in the future e.g. if they update the validation or further change their internal logic.

i also cross-checked the documentation of the "FastlyCDN - DM HTTP API" - it's definitely the case that the width parameter specifies the size of the output image. it's ignored if the width is larger than the original image.

2024-08-23 11:08 UTC, stefanseifert commented
i think we should merge it as-is?
it's still an improvement about the initial code, and it's line with the core component implementation.

the open issues are not related to our code, as we specify the right parameters in the URL although sometimes the output deviates a bit from the expected (but only in resolution, not in aspect ratio any longer). if this is a problem it should be tackled with adobe or tried to work around in separate PR.

2024-08-23 12:13 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/RelativeCroppingString.java
> +    return DECIMAL_FORMAT.format(Math.round(fraction * 1000d) / 10d);
What about a rounding check to have no values less than 0.0 and larger than 100.0 ?
The adobe service returns an error for wrong values.

2024-08-23 12:26 UTC, cnagel commented on src/main/java/io/wcm/handler/mediasource/dam/impl/weboptimized/RelativeCroppingString.java
> +    return DECIMAL_FORMAT.format(Math.round(fraction * 1000d) / 10d);
I've added the range check.

2024-08-26 08:51 UTC, stefanseifert approved these changes

2024-08-26 09:04 UTC, merged